name: 📚 Generate docs

on:
  push:
    branches:
      - docs

jobs:
  docs:
    name: 📚 Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.NPM_VERSION }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules
      - name: Generate docs
        run: npm run build-storybook
      - name: publish docs
        run: npm run deploy-storybook