name: Release
on:
  push:
    branches:
      - main
      - beta
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/test.yml
      - run: npm -v
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run release